---
title: "data_manipulation"
author: "Rui Huang"
date: "September 20, 2018"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
```
```{r}
options(tibble.print_min = 3)

litters_data = read_csv("./data/FAS_litters.csv",
  col_types = "ccddiiii")
litters_data = janitor::clean_names(litters_data)

pups_data = read_csv("./data/FAS_pups.csv",
  col_types = "ciiiii")
pups_data = janitor::clean_names(pups_data)
```

## Select variables

```{r}
select(litters_data, group, litter_number, gd0_weight, pups_born_alive)
```

```{r}
select(litters_data, group, litter_number, gest_day_0_weight = gd0_weight)
rename(litters_data, gest_day_0_weight = gd0_weight)
```
```{r}
select(litters_data, starts_with("gd"))
select(litters_data, litter_number, starts_with("pup"))
select(litters_data, litter_number, everything())
```

## Filter Observation

Do some filtering!

```{r}
filter(litters_data, gd0_weight < 25)
filter(litters_data, gd0_weight >= 25)

filter(litters_data, pups_born_alive == 8)
filter(litters_data, is.na(gd0_weight))

filter(litters_data, group == "Low8" | group == "Low7")
filter(litters_data, group %in% c("Con7", "Con8"))

filter(litters_data, pups_born_alive %in% 4:6)
filter(litters_data, pups_born_alive %in% 4:7, !is.na(gd0_weight))
```

## Mutate

Create variables

```{r}
mutate(litters_data,
       wt_gain = gd18_weight - gd0_weight,
       group = tolower(group))
```

```{r}
mutate(litters_data,
       wt_gain = gd18_weight - gd0_weight,
       wt_gain_squared = wt_gain)
```


## Arrange

Arrange the data...

```{r}
arrange(litters_data, gd0_weight)
arrange(litters_data, desc(pups_born_alive), gd0_weight)
```






